export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";
export const GET_ALL_DATA_STARTED = "GET_ALL_DATA_STARTED";
export const GET_ALL_DATA_FAILED = "GET_ALL_DATA_FAILED";

export const SELECT_CARD = "SELECT_CARD";
