export const GET_ALL_DATA_SUCCESS = "GET_ALL_DATA_SUCCESS";
export const GET_ALL_DATA_STARTED = "GET_ALL_DATA_STARTED";
export const GET_ALL_DATA_FAILED = "GET_ALL_DATA_FAILED";
export const GET_GAME_DATA_SUCCESS = "GET_GAME_DATA_SUCCESS";
export const GET_GAME_DATA_STARTED = "GET_GAME_DATA_STARTED";
export const GET_GAME_DATA_FAILED = "GET_GAME_DATA_FAILED";
export const GET_ALL_GAMES_SUCCESS = "GET_ALL_GAMES_SUCCESS";
export const GET_ALL_GAMES_STARTED = "GET_ALL_GAMES_STARTED";
export const GET_ALL_GAMES_FAILED = "GET_ALL_GAMES_FAILED";

export const SELECT_CARD = "SELECT_CARD";
export const SELECT_PILLAR = "SELECT_PILLAR";
export const SELECT_CARDS = "SELECT_CARDS";
export const FILTER_PILLARS = "FILTER_PILLARS";

export const CLOSE_MENU = "CLOSE_MENU";
export const OPEN_ADD_CARD_MENU = "OPEN_ADD_CARD_MENU";
export const OPEN_ADD_PILLAR_MENU = "OPEN_ADD_PILLAR_MENU";
export const ADD_CARD = "ADD_CARD";
export const ADD_PILLAR = "ADD_PILLAR";

export const NEW_GAME = "NEW_GAME";

export const SAVE_GAME = "SAVE_GAME";
export const SELECT_GAME = "SELECT_GAME";
export const SELECT_STARTING_DECK = "SELECT_STARTING_DECK";

export const DELETE_PILLAR = "DELETE_PILLAR";
export const DELETE_CARD = "DELETE_CARD";
